### ISSUE TITLE
GPU not detected

### ISSUE THREAD

**Issue by grassjelly** [dnovischi/jetson-nano-pythorch#2]
Hi, thanks for releasing this build for Pytorch on Jetson Nano. I managed to build the wheel on my host machine, however the library can't seem to detect the GPU when running `torch.cuda.is_available()` on Jetson Nano (Ubuntu 20.04, L4T-R32.6). I have the following installed `cuda-toolkit-10-2` `libcudnn8` `libcudnn8-dev` . 

Just wondering if you ever encountered such problem. Thank you!

**Comment by dnovischi** [comment]
Hi

That's pretty weird, I can't say that I encountered this problem before. However a possible workaround is try to do a clean distribution upgrade from ubuntu 18.04 with l4t-R32.6.1 to ubuntu 20.04 and then install the generated wheel.

Otherwise, as temporary replacement you can try to use a pre-built image from [Q-Engineering](https://qengineering.eu/install-pytorch-on-jetson-nano.html).

I'll leave this open, maybe someone can provide more insight.

**Comment by grassjelly** [comment]
Thanks for your reply. I created my own image using this tutorial https://github.com/pythops/jetson-nano-image/tree/3849a0f4d0144b81b9b1f6bfa71720ec71cf5567 . May I know which image did you test this on?

**Comment by dnovischi** [comment]
I test the builds on two images (one for JentsonNano 2GB and one for JetsonNano) created via distribution upgrade from the official ubuntu 18.04 nvidia release. Using custom images may introduce issues with the l4t gpu drivers ... lot's of moving parts and decencies there. 

Also you may want to try to use the docker in the development branch with your custom image (if you do ...comment out the torchaudio part, I still have to fix that part).

**Comment by grassjelly** [comment]
Okay, that's a great tip!  Do you mind sharing any links/materials I can follow on how to exactly replicate what you did on upgrading to 20.04 and keeping the GPU drivers intact. Really appreciate the help.

**Comment by dnovischi** [comment]
This is going to be very long, but here goes nothing

### Installing Ubuntu 20.04 through distribution upgrade from 18.04
1. Install the official ubuntu 18.04 image (see [here](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-2gb-devkit))
2. Insert the sd card into the nano and boot
3. Update and upgrade:

`sudo apt update;sudo apt upgrade -y`
4. Install latest jetpack:

`sudo apt install nvidia-jetpack`
5. Remove Chromium browser, upgrade and get rid of unused packages:
```bash
sudo apt remove --purge chromium-browser chromium-browser-l10n
sudo apt update
sudo apt upgrade
sudo apt autoremove
```
6. Install nano editor:.

`sudo apt install nano`

7. Next, you need to enable distribution upgrades in the update manager by setting prompt=normal in the `/etc/update-manager/release-upgrades` file.
As usual, close with `<Ctrl> + <X>, <Y>` and `<Enter>`.

`sudo nano /etc/update-manager/release-upgrades`

8. Change `Prompt=never` to `Prompt=normal`, save and exit.
9. With the update manager set, we need to refresh the software database again. Once done, you can reboot.

```bash
sudo apt update
sudo apt dist-upgrade
sudo reboot
```
10. With all preparations made, it's time for the upgrade to Ubuntu 20.04. 
It will take several hours. Unfortunately, some input is required throughout the procedure as there are questions to be answered. 
Check your screen now and then. Answer all questions with the suggested default value.

`sudo do-release-upgrade`
11. When the process finishes, **do not reboot!**
12. First, check that `WaylandEnable=false` is uncommented in the `/etc/gdm3/custom.conf` file.
13. Uncomment `Driver "nividia"` in the `/etc/X11/xorg.conf` file.
14. Finally, reset the upgrade manager to never (`Prompt=never`) and now reboot.

```bash
sudo nano /etc/gdm3/custom.conf
sudo nano /etc/X11/xorg.conf
sudo nano /etc/update-manager/release-upgrades
sudo reboot
```
15. Update, upgrade and auto-remove:
```bash
sudo apt update
sudo apt upgrade
sudo apt autoremove
```
16. Next, remove an annoying circular symbolic link in `/usr/share/applications` that makes the same app appear 86 times in your software overview.
```bash
# remove circular symlink
sudo rm /usr/share/applications/vpi1_demos
# remove distorted nvidia logo in top bar
cd /usr/share/nvpmodel_indicator
sudo mv nv_logo.svg no_logo.svg
```
17. Re-enable the original NVIDIA repositories, which were disabled during the upgrade. 
In the folder `/etc/apt/sources.list.d/` you will find the five files that needed to be changed. 
Open each file with `sudo` nano and remove the hash in front of the line to activate the repository.

18. Again, Update, upgrade and auto-remove:
```bash
sudo apt update
sudo apt upgrade
sudo apt autoremove
```
19. Some software packages, especially the CUDA software, requires a gcc version 8. 
We shall install this version besides the already available version 9. 
With a simple command, you can now switch between the two versions. 
The gcc compiler is always accompanied by the corresponding g++ compiler. 
The latter will also be installed.
```bash
# install gcc and g++ version 8
sudo apt install gcc-8 g++-8
# setup the gcc selector
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
# setup the g++ selector
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8
# if you want to make a selection use these commands
sudo update-alternatives --config gcc
sudo update-alternatives --config g++
```
20. You may run into problems upgrading Ubuntu 20.04 on your Jetson Nano after a while. 
The Software Updater cannot install all the packages listed. 
```bash
sudo apt --fix-broken
sudo apt intall -f
```

**Comment by grassjelly** [comment]
Thanks for the detailed reply. I'll close this for now but I'll be posting my results here. Cheers!

**Comment by grassjelly** [comment]
Hey @dnovischi . Thank you so much for the very detailed instructions. Pytorch can now detect Cuda.
